baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "I'm Tom"
author = "Thomas Johander"
description = "Call me Tom"
profilePicture = "images/profile.jpg"
